language: php

sudo: false

cache:
  directories:
    - $HOME/downloads
    - $HOME/.composer/cache

before_cache:
  - cp $HOME/.composer/composer.json $HOME/.composer/cache/
  - cp $HOME/.composer/composer.lock $HOME/.composer/cache/

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - 7

env:
    global:
        - BUILD_TYPE=code

matrix:
    include:
        - php: 5.6 # A PHP version needs to be selected even if we won't use it there
          env: BUILD_TYPE=doc # marker environment variable to make the build matrix more readable in the UI
          # Override the different steps of the build config
          language: python
          before_install: []
          install: pip install Sphinx sphinx_rtd_theme
          before_script: []
          script: sphinx-build -nW -b html -d docs/build/doctrees docs docs/build/html
          after_script: []

:before_install:
    - export DOWNLOADS_FOLDER=$HOME/downloads
    - if [ -e "$HOME/.composer/cache/composer.json" ]; then mv $HOME/.composer/cache/composer.json $HOME/.composer/; fi;
    - if [ -e "$HOME/.composer/cache/composer.lock" ]; then mv $HOME/.composer/cache/composer.lock $HOME/.composer/; fi;

install:
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - if [ ! -e "${DOWNLOADS_FOLDER}/ocular.phar" ]; then wget https://scrutinizer-ci.com/ocular.phar -O "${DOWNLOADS_FOLDER}/ocular.phar" -t 3; fi;
    - composer global require "brianium/paratest:~0.7" "phpunit/php-code-coverage:<=3.3.9" "satooshi/php-coveralls:^1.0" --no-update
    - composer global install --prefer-dist
    - composer install --prefer-dist

before_script:
    - sed -i -e "s,http://localhost,http://localhost:8000,g" phpunit.xml.dist
    - export DISPLAY=:99.0

    - ./tests/run_selenium.sh
    - ./tests/install_webserver.sh

    - mkdir -p build/logs

script:
    - if [ "$TRAVIS_PHP_VERSION" = "7" -o "$TRAVIS_PHP_VERSION" == "hhvm" ]; then phpunit --coverage-clover build/logs/clover.xml; fi;
    - if [ "$TRAVIS_PHP_VERSION" != "7" -a "$TRAVIS_PHP_VERSION" != "hhvm" ]; then paratest --coverage-clover build/logs/clover.xml; fi;

after_script:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then coveralls -v; fi;
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php "${DOWNLOADS_FOLDER}/ocular.phar" code-coverage:upload --format=php-clover build/logs/clover.xml; fi;

after_failure:
    - cat /tmp/webdriver_output.txt
    - cat /tmp/webserver_output.txt
