language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - 7

env:
    global:
        - BUILD_TYPE=code

matrix:
    include:
        - php: 5.6 # A PHP version needs to be selected even if we won't use it there
          env: BUILD_TYPE=doc # marker environment variable to make the build matrix more readable in the UI
          # Override the different steps of the build config
          language: python
          before_install: []
          install: pip install Sphinx sphinx_rtd_theme
          before_script: []
          script: sphinx-build -nW -b html -d docs/build/doctrees docs docs/build/html
          after_script: []

before_install:
    - composer require brianium/paratest:~0.7 --no-update
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then composer require satooshi/php-coveralls:dev-master --no-update; fi;

install:
    - composer update --prefer-source

before_script:
    - export WEB_FIXTURES_HOST=http://localhost
    - export WEB_FIXTURES_BROWSER=firefox
    - export DISPLAY=:99.0

    - ./tests/run_selenium.sh
    - sudo ./tests/install_webserver.sh

    - mkdir -p build/logs

script:
    - if [ "$TRAVIS_PHP_VERSION" = "7" -o "$TRAVIS_PHP_VERSION" == "hhvm" ]; then phpunit --coverage-clover build/logs/clover.xml; fi;
    - if [ "$TRAVIS_PHP_VERSION" != "7" -a "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./vendor/bin/paratest --coverage-clover build/logs/clover.xml; fi;

after_script:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar -t 3; fi;
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi;

after_failure:
    - cat /tmp/webdriver_output.txt
