language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - hhvm

before_script:
    - export WEB_FIXTURES_HOST=http://localhost
    - export WEB_FIXTURES_BROWSER=firefox

    - sh -e /etc/init.d/xvfb start
    - export DISPLAY=:99.0
    - sleep 4

    - curl -L http://selenium-release.storage.googleapis.com/2.41/selenium-server-standalone-2.41.0.jar > selenium.jar
    - java -jar selenium.jar > /dev/null 2> /tmp/webdriver_output.txt &

    - composer require satooshi/php-coveralls:dev-master --dev --prefer-source

    - sudo apt-get update > /dev/null
    - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 > /dev/null
    - sudo sed -i -e "s,/var/www,$(pwd),g" /etc/apache2/sites-available/default
    - sudo /etc/init.d/apache2 restart

script:
    - mkdir -p build/logs
    - ./vendor/bin/paratest --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v
    - wget https://scrutinizer-ci.com/ocular.phar -t 3
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

after_failure:
    - cat /tmp/webdriver_output.txt
